name: chat_core
description: Core library for skewr chat agent.
version: 0.0.1

environment:
  sdk: ^3.8.0

dependencies:
  equatable: ^2.0.7
  http: ^1.2.0
  json_annotation: ^4.11.0

dev_dependencies:
  build_runner: ^2.4.0
  json_serializable: ^6.9.0
  lints: ^5.0.0
  test: ^1.24.0
